package io.github.udarya.mockserver

data class MockStructure(
    /** class name generated by protoc from grpckt directory (e.g. com.test.TestAPIGrpcKt) */
    val kotlinGrpcClassName: String,
    /** service name from .proto file (e.g. TestAPI) */
    val serviceName: String
)

data class ServiceClass(
    val serviceName: String,
    val grpcClassName: String,
    val grpcImplClassName: String
)

data class MockScript(
    val serviceName: String,
    val script: String,
    val implementedClassName: String
)
